### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by pvinis** [artsy/relay-workshop#31]
I run through the exercises and here's what I had as feedback/ideas.

I might have missed some stuff so if you do some of these things, just ignore them. Also if you think things are not useful on in-scope or anything else, again, feel free to ignore. I won't be hurt :p.

- [x] For the first exercise (0), the command is `yarn start-ex-1`, but then I go to `localhost/ex-0`. Maybe the command should be `yarn start-ex-0`, or only use the `yarn start-exersices`?

- [x] In ex-0, at the end, watchman is required to watch for changes when i tried to yarn relay --watch. Somehow it said I didn't have watchman, so maybe a good thing to add `brew install watchman` in case people don't have it already.

- [x] In ex-1, the completed files, some imports are missing. Maybe important, maybe not.

- [x] Maybe add links on readme to all exercises` READMEs, for quick access.

- [x] I love the `hooooome` part, haha!

- [x] The way we check here:
```
if (!props || !props.artist) {
  return;
}
```
shouldn't that be return null?

- [x] Also, for the above code, maybe the `if` check can be different? I'm not sure how to, but we have had a few variations in eigen, and I'm not sure we have arrived at a best practice yet. I guess it can be updated later if we do have one. It was just a thought.

- [x] Can we add vscode autocomplete support for relay? It would be great to get that based on the scheme.

- [x] In `Artist1QR`, I had `<Artist1 artist={artist} />` instead of `props.artist`. I had to take a minute to compare code, which is not useful, in a tutorial. Maybe add a note, like **Make sure to change the `artist` prop, blablabla**.

- [x] Also, `({ props })`. This tripped me, I had `(props)`, without the `{}`. A note for that again?

- [x] I really liked the existence of 💻. I thought it could help to add some other emoji like 🎯 or something, to show what the goal of the exercise is. In ex-2, I had to scroll and read half-way down the README for it, so it would help to have it more obvious?

- [x] This relay naming restrictions, like `Artist2_artist`.. Is that explained anywhere? I don't know if there is tooling to automate this, but if we don't have it, then it would be helpful to explain that relay needs this kind of naming and we need to do that, rather than just copying the name from the tutorial.

- [x] I liked the `Artist2_artist` part a lot. After this works, I kinda wanted to add a new field and display it, just to "prove" to myself that the fragment actually works. Maybe adding a new field to confirm that is cool?

- [x] explain this kind of errors:
```
Parse error: Error: RelayFindGraphQLTags: Container fragment names must be `<ModuleName>_<propName>`. Got `Blabla2Heading_artist`, expected `Artist2Heading_artist`. in "exercises/02-Fragment-Container/Artist2Heading.tsx"
Watching for changes to ts/tsx...
```
I guess this goes with the item a couple of bullets above.

- [x] I only saw the "common mistakes" part at the bottom when I was done with the exercise. I think adding a little thingy like <sup>this</sup> would help. Like in the part where we need the name, have one of these to link to the bottom, directly to the "naming incorrectly" part.

That's all I thought while going through the workshop. Super cool work! :)

**Comment by pepopowitz** [comment]
Wow @pvinis thank you so much for this!! I'll take some time later this week to respond & address.

**Comment by pepopowitz** [comment]
#33 addresses many of the issues here, but here are some notes for things that PR doesn't address directly:

> In ex-1, the completed files, some imports are missing. Maybe important, maybe not.

We opted not to correct this. If anyone in the future feels it's necessary, I welcome a PR with open arms :) 

> Also, for the above code, maybe the if check can be different? I'm not sure how to, but we have had a few variations in eigen, and I'm not sure we have arrived at a best practice yet. I guess it can be updated later if we do have one. It was just a thought.

Again, we're open to more concrete suggestions via PR, but not going to address this now.

> Can we add vscode autocomplete support for relay? It would be great to get that based on the scheme.

This is a good idea - I'm not sure what it takes to make it happen though. Can you point us in a direction?

> I liked the Artist2_artist part a lot. After this works, I kinda wanted to add a new field and display it, just to "prove" to myself that the fragment actually works. Maybe adding a new field to confirm that is cool?

Another good idea, but this one takes a bit more effort than other issues here due to it including new content. We welcome a PR :)

**Comment by pepopowitz** [comment]
Closing this due to the associated PR, but feel free to open any more focused issues based on our comments above!
